# Use the latest node Debian slim base image
# This makes installing yarn dep much easier
ARG BASE_IMAGE=node:20-bookworm-slim
FROM ${BASE_IMAGE}

# Switch to bash shell
SHELL ["/bin/bash", "-c"]
WORKDIR /contracts

# copy script configs
COPY ./docker/templates/ /contracts/docker/templates/

COPY ./docker/scripts/gen-configs.sh /contracts/docker/scripts/gen-configs.sh

ENTRYPOINT ["/bin/bash", "/contracts/docker/scripts/gen-configs.sh"]
