# Use the latest node Debian slim base image
# This makes installing yarn dep much easier
ARG BASE_IMAGE=node:20-bookworm-slim
FROM ${BASE_IMAGE}

# Switch to bash shell
SHELL ["/bin/bash", "-c"]
WORKDIR /contracts

# copy scripts
COPY ./docker/scripts/verify.sh /contracts/docker/scripts/verify.sh
COPY ./docker/scripts/verify-contracts.js /contracts/docker/scripts/verify-contracts.js
COPY ./node_modules/toml /contracts/node_modules/toml

ENTRYPOINT ["/bin/bash", "/contracts/docker/scripts/verify.sh"]
